name: Deploy to production
permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy-production:
    name: Deploy to prod on merge to main branch
    uses: Informasjonsforvaltning/workflows/.github/workflows/build-deploy.yaml@main
    with:
      app_name: fdk-community-service
      environment: prod
      cluster: digdir-fdk-prod
      dockerfile: prod.Dockerfile
      snapshot_disk: fdk-prod-community-service
      snapshot_name: autodeploy-prod-community-service
      snapshot_zone: europe-north1-a
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_PROD_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
